spring:
  datasource:
    url: jdbc:mysql://localhost:3306/liquibase_db
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver

  liquibase:
    change-log: classpath:/db/changelog/liquibase-demo.xml
    enabled: true
    drop-first: false
